---
- name: CONFIGURE KINIT
  hosts: all
#  become: yes
  connection: ssh
  gather_facts: no

  tasks:
  - name: INSTALL PEXPECT REQUIRED FOR EXPECT MODULE
    yum:
      name: pexpect
      state: latest
  - name: KINIT ADMIN
    expect:
      command: kinit admin
      responses:
        (?i)password: "{{ my_kerberos_master_password }}"
