---
- name: CONFIGURE KINIT
  hosts: all
#  become: yes
  connection: ssh
  gather_facts: no

  tasks:
  - name: EXECUTE EXPECT TO GENERATE KERBEROS TICKET
    shell: |
      set timeout 60
      kinit admin
      expect "Password for admin@EXAMPLE.COM: "
      send "{{ my_kerberos_master_password }}"
    args:
      executable: /usr/bin/expect
    register: shelloutput

  - name: OUTPUT SCRIPT DETAIL
    debug:
      msg: "{{ shelloutput }}"


#  - name: INSTALL PEXPECT REQUIRED FOR EXPECT MODULE
#    yum:
#      name: pexpect
#      state: latest
#  - name: KINIT ADMIN
#    expect:
#      command: kinit admin
#      responses:
#        (?i)password: "{{ my_kerberos_master_password }}"
