---
- name: CONFIGURE AND RESTART IDM
  hosts: all
#  become: yes
  connection: ssh

  tasks:
  - name: KINIT ADMIN
    expect:
      command: kinit admin
      responses:
        (?i)password: "{{ my_kerberos_master_password }}"
